#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

defined('DEFAULT_PATH') or define('DEFAULT_PATH', realpath(dirname(__FILE__)));
defined('DOTENV_PATH') or define('DOTENV_PATH', DEFAULT_PATH . DIRECTORY_SEPARATOR);
defined('DOTENV_FILE') or define('DOTENV_FILE', '.env.local');
defined('DOTENV_OVERLOAD') or define('DOTENV_OVERLOAD', false);

defined('YII_DEBUG') or define('YII_DEBUG', false);
defined('YII_ENV') or define('YII_ENV', 'prod');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';
require __DIR__ . '/console/config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/common/config/main.php',
    require __DIR__ . '/common/config/main-local.php',
    require __DIR__ . '/console/config/main.php',
    require __DIR__ . '/console/config/main-local.php'
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
